Class {
	#name : #ManifestKozStef,
	#superclass : #Object,
	#category : #KozStef
}

{ #category : #'meta data' }
ManifestKozStef class >> rejectClasses [
^ #()
]

{ #category : #'meta data' }
ManifestKozStef class >> rejectRules [
^ #(78 24 115)
]

{ #category : #'meta data' }
ManifestKozStef class >> rule12V1FalsePositive [
^ #(#('(RGMethodDefinition className: ''StefSite'' selector: #title isMetaSide: false)' #(#'15 March 2012' #'9:55:55 am')) #('(RGMethodDefinition className: ''StefSite class'' selector: #defaultCSS isMetaSide: true)' #(#'15 March 2012' #'9:56:04 am')) )
]

{ #category : #'meta data' }
ManifestKozStef class >> rule15V1FalsePositive [
^ #(#('(RGClassDefinition named: #StefSite)' #(#'15 March 2012' #'9:56:45 am')) )
]

{ #category : #'meta data' }
ManifestKozStef class >> rule50V1FalsePositive [
^ #(#('(RGMethodDefinition className: ''StefSite'' selector: #subtopicKey: isMetaSide: false)' #(#'15 March 2012' #'10:17:16 am')) )
]

{ #category : #'meta data' }
ManifestKozStef class >> rule76V1FalsePositive [
^ #(#('(RGMethodDefinition className: ''StefSite'' selector: #createResearchSubTopicPages isMetaSide: false)' #(#'15 March 2012' #'10:03:31 am')) #('(RGMethodDefinition className: ''StefSite'' selector: #sectionAwardsAndIndexes isMetaSide: false)' #(#'15 March 2012' #'10:03:38 am')) )
]

{ #category : #'meta data' }
ManifestKozStef class >> rule8V1FalsePositive [
^ #(#('(RGClassDefinition named: #StefSite)' #(#'15 March 2012' #'9:51:07 am')) #('(RGClassDefinition named: #ManifestKozStef)' #(#'15 March 2012' #'9:51:27 am')) )
]

{ #category : #'meta data' }
ManifestKozStef class >> rule90V1FalsePositive [
^ #(#('(RGMethodDefinition className: ''StefSite'' selector: #addEditorialNavigation isMetaSide: false)' #(#'15 March 2012' #'10:13:41 am')) #('(RGMethodDefinition className: ''StefSite'' selector: #addSoftwareEvolutionNavigation isMetaSide: false)' #(#'15 March 2012' #'10:13:46 am')) #('(RGMethodDefinition className: ''StefSite'' selector: #addLanguageNavigation isMetaSide: false)' #(#'15 March 2012' #'10:13:50 am')) )
]
